version: "2"

networks:
  app_network:
    driver: bridge

services:

  master:
    build:
      context: ../docker-images/spark-hdfs-node
    image: dilettalagom/spark-hdfs-node
    container_name: master
    hostname: master
    networks:
      - app_network
    ports:
      - "9870:9870" # hdfs ui
      - "54310:54310" # hdfs
      - "43211:43211" #remote intellij debugging
      - "18080:18080" #spark history ui
    volumes:
      - ./target:/target
    stdin_open: true
    tty: true
    command: bash -c "sh start-services.sh"


  worker1:
    image: dilettalagom/spark-hdfs-node
    container_name: worker1
    hostname: worker1
    networks:
      - app_network
    ports:
      - "9861:9861"
    depends_on:
      - master
    volumes:
      - ./target:/target
    stdin_open: true
    tty: true
    command: bash -c "sh start-services.sh"


  worker2:
   image: dilettalagom/spark-hdfs-node
   container_name: worker2
   hostname: worker2
   networks:
     - app_network
   ports:
     - "9862:9861"
   depends_on:
     - master
   volumes:
     - ./target:/target
   stdin_open: true
   tty: true
   command: bash -c "sh start-services.sh"

  worker3:
    image: dilettalagom/spark-hdfs-node
    container_name: worker3
    hostname: worker3
    networks:
      - app_network
    ports:
       - "9863:9861"
    depends_on:
      - master
    volumes:
      - ./target:/target
    stdin_open: true
    tty: true
    command: bash -c "sh start-services.sh"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - app_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi:
    build:
      context: ../docker-images/nifi-node
    image: dilettalagom/nifi
    container_name: nifi
    depends_on:
      - master
    hostname: nifi
    networks:
      - app_network
    volumes:
      - ./nifi-flow:/usr/local/nifi-1.11.4/conf/flow
      - ./nifi-scripts:/usr/local/nifi-1.11.4/data/nifi-scripts
    ports:
      - "4040:4040"
      - "43212:43212"
      - "43210:43210" #remote intellij degugging port

    stdin_open: true
    tty: true
