{
 "title": "WorldMapQuery3",
 "time": { "from": "2020-02-20T02:16:52.000Z", "to": "2020-06-01T09:53:30.053Z" },
 "templating": {
  "list": [
   { "name": "Anno", "query": "2020" },
   { "name": "Mese", "query": "06" }
  ]
 },
 "panels": [
  {
   "title": "WorldMapQuery3",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "data": "{\n  \"anno\": \"$Anno\",\n  \"mese\": \"$Mese\"\n}",
     "target": "query3",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Query 1",
   "type": "graph",
   "description": "Andamento del numero dei guariti e dei tamponi in Italia",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "query1", "type": "timeseries" }
   ]
  },
  {
   "title": "Query2",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "targets": [
    { "target": "query2", "type": "timeseries" }
   ]
  }
 ]
}