{
 "title": "COVID19",
 "time": { "from": "2020-02-24T00:00:00.000Z", "to": "2020-05-25T00:00:00.000Z" },
 "panels": [
  {
   "title": "Query 3",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "query3", "type": "timeseries" }
   ]
  },
  {
   "title": "Query 2",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "target": "query2", "type": "timeseries" }
   ]
  },
  {
   "title": "Query 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "query1", "type": "timeseries" }
   ]
  }
 ]
}